=== ebarra/BDNR_ejemplos/xml_xsd/ejemplo_equipo_futbol/misxsds/equipo.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema targetNamespace="http://upm.es/xmlns/equipo"
           xmlns:tns="http://upm.es/xmlns/equipo"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
  <xs:element name="equipo">
    <xs:complexType>
        <xs:all>
          <xs:element name="nombre" type="xs:string"/>
          <xs:element name="ciudad" type="xs:string"/>
          <xs:element name="provincia" type="xs:string"/>
          <xs:element name="pais" type="xs:string"/>
          <xs:element name="estadio" type="xs:string"/>
          <xs:element name="capacidad" type="xs:integer"/>
          <xs:element name="entrenador" type="xs:string"/>
          <xs:element name="plantilla">
            <xs:complexType>
                <xs:sequence maxOccurs="50">
                  <xs:element name="jugador" type="tns:jugadorInfo"/>
                </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:all>
        <xs:attribute name="id" use="required" >
          <xs:simpleType>
            <xs:restriction base="xs:integer">
                <xs:totalDigits value="5"/>
            </xs:restriction>
          </xs:simpleType>   
        </xs:attribute>     
    </xs:complexType>
    </xs:element>
    <xs:complexType name="jugadorInfo">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string" />
      <xs:element name="apellidos" type="xs:string" />
      <xs:element name="posicion" type="xs:string" />
      <xs:element name="dorsal" type="xs:integer" />
    </xs:sequence>
    </xs:complexType>
</xs:schema>

=== ebarra/BDNR_ejemplos/xml_xsd/ejemplo_equipo_futbol/equipo.xml
<?xml version="1.0" encoding="UTF-8"?>
<equipo xmlns="http://upm.es/xmlns/equipo" 
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:schemaLocation="http://upm.es/xmlns/equipo misxsds/equipo.xsd" 
    id="783">
    <nombre>Real Madrid</nombre>
    <ciudad>Madrid</ciudad>
    <provincia>Madrid</provincia>
    <pais>España</pais>
    <estadio>Santiago Bernabeu</estadio>
    <capacidad>81044</capacidad>
    <entrenador>Zinedine Zidane</entrenador>
    <plantilla>
        <jugador>
            <nombre>Thibaut</nombre>
            <apellidos>Courtois</apellidos>
            <posicion>Portero</posicion>
            <dorsal>1</dorsal>
        </jugador>
        <jugador>
            <nombre>Daniel</nombre>
            <apellidos>Carvajal</apellidos>
            <posicion>Lateral Derecho</posicion>
            <dorsal>2</dorsal>
        </jugador>
        <jugador>
            <nombre>David</nombre>
            <apellidos>Alaba</apellidos>
            <posicion>Lateral Izquierdo</posicion>
            <dorsal>4</dorsal>
        </jugador>
        <jugador>
            <nombre>Nacho</nombre>
            <apellidos>Fernández</apellidos>
            <posicion>Central</posicion>
            <dorsal>6</dorsal>
        </jugador>
        <jugador>
            <nombre>Lucas</nombre>
            <apellidos>Vázquez</apellidos>
            <posicion>Extremo Derecho</posicion>
            <dorsal>17</dorsal>
        </jugador>
        <jugador>
            <nombre>Luka</nombre>
            <apellidos>Modric</apellidos>
            <posicion>Medio Centro</posicion>
            <dorsal>10</dorsal>
        </jugador>
        <jugador>
            <nombre>Toni</nombre>
            <apellidos>Kroos</apellidos>
            <posicion>Medio Centro</posicion>
            <dorsal>8</dorsal>
        </jugador>
        <jugador>
            <nombre>Vinicius</nombre>
            <apellidos>Jr</apellidos>
            <posicion>Extremo Izquierdo</posicion>
            <dorsal>20</dorsal>
        </jugador>
        <jugador>
            <nombre>Jude</nombre>
            <apellidos>Bellingham</apellidos>
            <posicion>Medio Centro</posicion>
            <dorsal>22</dorsal>
        </jugador>
    </plantilla>
</equipo>
