=== ebarra/BDNR_ejemplos/alumnos_borrar/banda.xsd
<?xml version="1.0" encoding="UTF-8"?>

<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
targetNamespace="https://www.w3schools.com"
xmlns="https://www.w3schools.com"
elementFormDefault="qualified">
  <xs:element name="band">
    <xs:complexType>
      <xs:sequence>
        <xs:element type="xs:string" name="group"/>
        <xs:element type="xs:string" name="description"/>
        <xs:element name="members">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="member" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="mem_name"/>
                    <xs:element type="xs:string" name="instrument"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="albums">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="album" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="alb_name"/>
                    <xs:element type="xs:string" name="song" minOccurs="1" maxOccurs="unbounded"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="concerts">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="concert" minOccurs="0" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:string" name="city"/>
                    <xs:element type="xs:string" name="place"/>
                    <xs:element type="xs:string" name="date"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>





<!--He usado la pÃ¡gina freeformatter.com como ayuda para hacer este xsd-->

=== ebarra/BDNR_ejemplos/alumnos_borrar/banda.xml
<?xml version="1.0" encoding="UTF-8"?>

<band xmlns="https://www.w3schools.com"
xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
xsi:schemaLocation="https://www.w3schools.com banda.xsd">
    <group>Red Hot Chili Peppers</group>
    <description>American rock band formed in Los Angeles in 1983</description>
    <members>
        <member>
            <mem_name>Anthony Kiedis</mem_name>
            <instrument>vocalist</instrument>
        </member>
        <member>
            <mem_name>Flea</mem_name>
            <instrument>bass guitar</instrument>
        </member>
        <member>
            <mem_name>Chad Smith</mem_name>
            <instrument>drums</instrument>
        </member>
        <member>
            <mem_name>John Frusciante</mem_name>
            <instrument>guitar</instrument>
        </member>
    </members>
    <albums>
        <album>
            <alb_name>Californication</alb_name>
            <song>Around the world</song>
            <song>Parallel universe</song>
            <song>Scar tissue</song>
        </album>
        <album>
            <alb_name>By the way</alb_name>
            <song>By the way</song>
            <song>Can't stop</song>
            <song>The zephyr song</song>
        </album>
    </albums>
    <concerts>
        <concert>
            <city>Sevilla</city>
            <place>Estadio de la Cartuja</place>
            <date>4/6/22</date>
        </concert>
        <concert>
            <city>Barcelona</city>
            <place>Estadi Ol√≠mpic</place>
            <date>7/6/22</date>
        </concert>
    </concerts>
</band>
