=== ebarra/BDNR_ejemplos/xml_xsd/ejemplo_catalogo/catalogo.xsd
<?xml version="1.0" encoding="utf-8" ?>
<xs:schema targetNamespace="http://upm.es/xmlns/catalogo"
           xmlns:tns="http://upm.es/xmlns/catalogo"
           xmlns:xs="http://www.w3.org/2001/XMLSchema"
           elementFormDefault="qualified">
  <xs:element name="catalogo">
    <xs:complexType>
        <xs:all>
          <xs:element name="fecha" type="xs:date"/>
          <xs:element name="productos">
            <xs:complexType>
                <xs:sequence maxOccurs="10">
                  <xs:element name="producto" type="tns:productInfo"/>
                </xs:sequence>
            </xs:complexType>
          </xs:element>
        </xs:all>
        <xs:attribute name="id" use="required" >
          <xs:simpleType>
            <xs:restriction base="xs:integer">
                <!--<xs:pattern value="[0-9][0-9][0-9]"/>-->
                <xs:totalDigits value="5"/>
            </xs:restriction>
          </xs:simpleType>   
        </xs:attribute>     
    </xs:complexType>
  </xs:element>
  <xs:complexType name="productInfo">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string" />
      <xs:element name="categorÃ­a" type="xs:string" />
      <xs:element name="precio" type="xs:double" />
      <xs:element name="imagen">
          <xs:simpleType>
              <xs:restriction base="xs:anyURI">
                  <xs:pattern value="http://.+" />
              </xs:restriction>
          </xs:simpleType>
      </xs:element>
    </xs:sequence>
  </xs:complexType>
</xs:schema>

=== ebarra/BDNR_ejemplos/xml_xsd/ejemplo catalogo/catalogo.xml
<?xml version="1.0"?>
<catalogo xmlns="http://upm.es/xmlns/catalogo" 
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://upm.es/xmlns/catalogo catalogo.xsd" 
          id="783">
  <fecha>2021-09-14</fecha>
  <productos>
    <producto>
      <nombre>Puzzle</nombre>
      <categoría>Juguetes</categoría> 
      <precio>13.60</precio>
      <imagen>http://example.com/images/puzzle.png</imagen>
    </producto>
    <producto>
      <nombre>Muñeco</nombre>
      <categoría>Juguetes</categoría> 
      <precio>15.00</precio>
      <imagen>http://example.com/images/muneco.png</imagen>
    </producto>
  </productos>
</catalogo>
